using System.Collections.Generic;

namespace BioSAK.Localization
{
    /// <summary>
    /// UI text tables (interface labels only).
    /// Analysis results, exported files, clipboard output and chart data
    /// are NEVER taken from here - they stay exactly as they were.
    /// </summary>
    internal static class LocalizationStrings
    {
        public static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "ACTB", "ACTB" },
            { "ADD_CUSTOM_SEQUENCE", "ADD CUSTOM SEQUENCE" },
            { "About", "About" },
            { "About_BioXAK", "About BioXAK" },
            { "Accepts_Symbol_ENSG_ID_NCBI_ID", "Accepts: Symbol, ENSG ID, NCBI ID" },
            { "Accession_NM_NG_NR", "Accession (NM_ / NG_ / NR_)" },
            { "Actinide", "Actinide" },
            { "Active_Template_Sequence", "Active Template Sequence" },
            { "Add", "+ Add" },
            { "Add_2", "Add:" },
            { "Add_Feature", "Add Feature" },
            { "Add_Label", "+ Add Label" },
            { "Add_Label_2", "▶ Add Label" },
            { "Add_Panel", "➕ Add Panel" },
            { "Add_Row", "+ Add Row" },
            { "Add_Sequence", "➕ Add Sequence" },
            { "Add_Text_Box", "Add Text Box" },
            { "Add_restriction_enzyme_overhangs", "Add restriction enzyme overhangs" },
            { "Add_to_Blot_Images", "➕  Add to Blot Images" },
            { "Adjust_then_add_to_Blot_Images", "Adjust then add to Blot Images" },
            { "Alkali", "Alkali" },
            { "Alkaline_Earth", "Alkaline Earth" },
            { "All_Bars", "All Bars" },
            { "Analysis_Parameters_Guide", "📘 Analysis Parameters Guide" },
            { "Analyze", "Analyze" },
            { "Analyze_All_Enzymes", "Analyze All Enzymes" },
            { "Analyze_Co_Expression", "Analyze Co-Expression" },
            { "Analyze_Find_Complement", "Analyze / Find Complement" },
            { "Analyze_effects_of_Series_and_X_value_requir", "Analyze effects of Series and X value (requires multiple rows)" },
            { "Analyze_protein_truncation_caused_by_1_2_fra", "Analyze protein truncation caused by +1/+2 frameshift after Cas9 cleavage" },
            { "Angle", "Angle" },
            { "Antibody_name", "Antibody name:" },
            { "Antibody_name_for_selected_blot", "Antibody name for selected blot:" },
            { "Any_Self_Comp", "Any Self-Comp" },
            { "Apply", "Apply" },
            { "Apply_All_Gates_to_Current_Sample", "📋 Apply All Gates to Current Sample" },
            { "Apply_Compensation", "Apply Compensation" },
            { "Apply_gate_regions_to_current_sample", "Apply gate regions to current sample:" },
            { "Arrow_Direction", "Arrow Direction" },
            { "Arrows", "Arrows" },
            { "Auto", "Auto" },
            { "Auto_Detect", "Auto Detect" },
            { "Auto_Detect_Symbol_Ensembl_ENSG_Entrez_numbe", "💡 Auto Detect: Symbol, Ensembl (ENSG...), Entrez (numbers), HGNC (HGNC:...)" },
            { "Auto_Pick_Parameters", "Auto-Pick Parameters" },
            { "Auto_Pick_Primers", "🔍 Auto-Pick Primers" },
            { "Auto_Pick_optimal_primer_pairs", "Auto — Pick optimal primer pairs" },
            { "Auto_Picked_Primer_Pairs", "🏆 Auto-Picked Primer Pairs" },
            { "Auto_Scale_round_to_nice_numbers", "Auto Scale (round to nice numbers)" },
            { "Auto_apply_on_file_switch", "Auto-apply on file switch" },
            { "Auto_arrange_and_annotate_blot_images", "Auto-arrange and annotate blot images" },
            { "Available_Cancers", "Available Cancers" },
            { "Avg", "Avg" },
            { "Axis_Break_Segment", "Axis Break (Segment)" },
            { "Axis_Range_empty_auto", "Axis Range (empty = auto)" },
            { "Axis_Settings", "Axis Settings" },
            { "Axis_Title", "Axis Title" },
            { "BCA_Conc_Calculator", "BCA Conc. Calculator" },
            { "BCA_Concentration_Calculator_Standard_curve", "📐  BCA Concentration Calculator  —  Standard curve-based protein quantification" },
            { "BLAST", "BLAST" },
            { "BLAST_Selected", "🔬 BLAST Selected" },
            { "Back", "← Back" },
            { "Bake_crop_selected_region_fills_the_preview", "Bake crop: selected region fills the preview" },
            { "Bar_Chart", "Bar Chart" },
            { "Base", "Base:" },
            { "BioXAK", "BioXAK" },
            { "BioXAK_Biology_X_Analysis_Kit", "BioXAK - Biology X Analysis Kit" },
            { "BioXAK_TCGA_Data_Initialization", "BioXAK — TCGA Data Initialization" },
            { "BioXAK_is_a_comprehensive_bioinformatics_too", "BioXAK is a comprehensive bioinformatics toolkit for life science researchers — an all-in-one desktop platform covering cancer genomics, CRISPR design, flow cytometry, sequence analysis, and laboratory calculations." },
            { "Biology_X_Analysis_Kit", "Biology X Analysis Kit" },
            { "Biotype", "Biotype" },
            { "Blot_Images", "Blot Images" },
            { "Blot_display_width", "Blot display width" },
            { "Blunt", "Blunt" },
            { "Bold", "Bold" },
            { "Border", "Border:" },
            { "Border_0_5_mm_Height_scales_proportionally", "Border = 0.5 mm  |  Height scales proportionally" },
            { "Border_Color", "Border Color:" },
            { "Border_Width", "Border Width:" },
            { "Both", "↔ Both" },
            { "Box_Plot", "📊 Box Plot" },
            { "Break_End", "Break End:" },
            { "Break_Start", "Break Start:" },
            { "Brightness_Levels", "Brightness Levels" },
            { "Buffer", "Buffer:" },
            { "Buffer_L", "Buffer (µL)" },
            { "CALCULATE_ALL", "CALCULATE ALL" },
            { "CDS", "CDS" },
            { "CHEMICAL", "CHEMICAL" },
            { "CLONING", "CLONING" },
            { "CLONING_2", "🔬 CLONING" },
            { "CONTACT", "📬  CONTACT" },
            { "CRISPR_GENE_EDITING", "CRISPR / GENE EDITING" },
            { "CRISPR_GENE_EDITING_2", "✂️  CRISPR / GENE EDITING" },
            { "Calculate", "Calculate" },
            { "Cancel", "Cancel" },
            { "Cancer", "Cancer" },
            { "Cancer_Type_Selection", "📊 Cancer Type Selection" },
            { "Chart", "Chart" },
            { "Chart_Settings", "Chart Settings" },
            { "Chart_Title", "Chart Title:" },
            { "Chart_Type", "Chart Type" },
            { "Chart_height_px", "Chart height (px)" },
            { "Chart_width_px", "Chart width (px)" },
            { "Chemical_Formula", "Chemical Formula" },
            { "Choose", "Choose..." },
            { "Choose_Color", "Choose Color" },
            { "Choose_Color_2", "Choose Color..." },
            { "Circular", "Circular" },
            { "Circular_Linear", "Circular / Linear" },
            { "Clear", "Clear" },
            { "Clear_2", "🗑️ Clear" },
            { "Clear_3", "✕ Clear" },
            { "Clear_All", "🗑️ Clear All" },
            { "Clear_All_2", "Clear All" },
            { "Clear_All_3", "🗑 Clear All" },
            { "Clear_All_Gates", "🗑️ Clear All Gates" },
            { "Clear_All_Highlights", "Clear All Highlights" },
            { "Click_Find_sgRNAs_in_CDS_after_loading_gene", "Click 'Find sgRNAs in CDS' after loading gene" },
            { "Click_and_drag_on_the_gene_map_above_to_sele", "💡 Click and drag on the gene map above to select a region as your primer design template." },
            { "Click_for_explanation", "Click for explanation" },
            { "Click_on_preview_to_place_a_side_label_line", "Click on preview to place a side label line" },
            { "Click_set_Left_then_Right_boundary_alternate", "Click: set Left then Right boundary alternately. Right-click: remove nearest." },
            { "Click_to_add_vertices_double_click_to_comple", "💡 Click to add vertices, double-click to complete polygon (min 3 points)" },
            { "Click_to_copy_email_address", "Click to copy email address" },
            { "Click_to_expand_collapse", "Click to expand/collapse" },
            { "Click_to_place_lane_center_Right_click_to_re", "Click to place lane center. Right-click to remove." },
            { "Click_to_preview_primer_details_below", "💡 Click to preview primer details below." },
            { "Click_to_show_above_below_percentages", "💡 Click to show above/below percentages" },
            { "Clone", "📋 Clone" },
            { "Clone_Insert_into_Vector", "🧬 Clone Insert into Vector" },
            { "Close", "Close" },
            { "Co_Expression", "🔗 Co-Expression" },
            { "Color", "Color:" },
            { "Column", "📊  Column" },
            { "Column_2", "📊 Column" },
            { "Column_Chart", "Column Chart" },
            { "Coming_soon", "Coming soon!" },
            { "Compare_different_X_values_within_one_series", "Compare different X values within one series" },
            { "Compare_multiple_series_at_a_specific_X_valu", "Compare multiple series at a specific X value" },
            { "Compare_two_series_at_a_specific_X_value_usi", "Compare two series at a specific X value using replicate data" },
            { "Compares_Tumor_vs_Normal", "  (Compares Tumor vs Normal)" },
            { "Compensation", "Compensation" },
            { "Complement", "Complement" },
            { "Conc", "Conc." },
            { "Conc_g_L", "Conc. (µg/µL)" },
            { "Conc_ng_L", "Conc. (ng/µL)" },
            { "Concentration", "Concentration:" },
            { "Concentration_Calculator", "Concentration Calculator" },
            { "Concentration_Calculator_Molar_concentration", "🧫  Concentration Calculator  —  Molar concentration and dilution tools" },
            { "Condition_Labels", "Condition Labels" },
            { "Condition_rows", "Condition rows:" },
            { "Conditions_for_missing_strand", "Conditions for missing strand" },
            { "Connect_scatter_points_with_lines", "Connect scatter points with lines" },
            { "Connecting", "Connecting..." },
            { "Contour_Colormap", "Contour Colormap:" },
            { "Contour_Plot", "Contour Plot" },
            { "Conversion_Results", "📊 Conversion Results" },
            { "Convert", "🔄 Convert" },
            { "Convert_to_Grayscale", "Convert to Grayscale" },
            { "Copy", "Copy" },
            { "Copy_2", "📋 Copy" },
            { "Copy_All", "📋 Copy All" },
            { "Copy_All_2", "Copy All" },
            { "Copy_Cell_s", "Copy Cell(s)" },
            { "Copy_Column", "Copy Column" },
            { "Copy_Eq", "📋 Copy Eq" },
            { "Copy_Not_Found_IDs", "📋 Copy Not Found IDs" },
            { "Copy_R", "📋 Copy R²" },
            { "Copy_Recipe_Table", "Copy Recipe Table" },
            { "Copy_Results", "📋 Copy Results" },
            { "Copy_Row_s", "Copy Row(s)" },
            { "Copy_Sequence", "📋 Copy Sequence" },
            { "Copy_Stats", "📋 Copy Stats" },
            { "Copy_Table", "📋 Copy Table" },
            { "Copy_to_Clipboard", "📄 Copy to Clipboard" },
            { "Copy_to_Clipboard_2", "📋 Copy to Clipboard" },
            { "Count", "Count" },
            { "Crop", "✂ Crop" },
            { "Ctrl_C", "Ctrl+C" },
            { "Custom_Color_RGB", "Custom Color (RGB)" },
            { "Cut_Positions", "Cut Positions" },
            { "Cut_sites_select_or_auto_detect", "Cut sites (select or auto-detect):" },
            { "Cuts", "Cuts" },
            { "Cycle_fill_pattern", "Cycle fill pattern" },
            { "DNA", "DNA" },
            { "DNA_Sequence", "DNA Sequence:" },
            { "DNA_TOOLS", "DNA TOOLS" },
            { "DNA_TOOLS_2", "🔤  DNA TOOLS" },
            { "Data_Points", "Data Points" },
            { "Data_source_HGNC_Human_NCBI_Gene_Other_speci", "Data source: HGNC (Human), NCBI Gene (Other species)" },
            { "Database_Information", "ℹ️ Database Information" },
            { "Delete", "🗑 Delete" },
            { "Delete_2", "Delete" },
            { "Delete_Del", "🗑 Delete (Del)" },
            { "Delete_Selected_Row", "Delete Selected Row" },
            { "Demo_FCS", "🧪 Demo FCS" },
            { "Descriptive_Statistics", "📋 Descriptive Statistics" },
            { "Design_Mode", "Design Mode" },
            { "Details", "Details" },
            { "Digest", "Digest" },
            { "Digest_2", "✂️ Digest" },
            { "Digestion_Results", "Digestion Results:" },
            { "Direct_Sequence_Input", "📝 Direct Sequence Input" },
            { "Direction", "Direction" },
            { "Divalent_cation_concentration_mM", "Divalent cation concentration (mM)" },
            { "Divisions", "Divisions:" },
            { "Dot_Colormap", "Dot Colormap:" },
            { "Dot_Plot", "Dot Plot" },
            { "Double_click_chart_to_edit_Ctrl_A_Select_All", "Double-click chart to edit | Ctrl+A: Select All | Del: Delete" },
            { "Down", "↓ Down" },
            { "Download_Selected", "⬇️ Download Selected" },
            { "Drag_on_map_to_view_sequence_Ready", "Drag on map to view sequence. Ready." },
            { "Edit_Bar", "Edit Bar" },
            { "Edit_Bar_Style", "Edit Bar Style" },
            { "Edit_Bar_Styles", "Edit Bar Styles" },
            { "Edit_Bar_Styles_2", "🎨 Edit Bar Styles" },
            { "Edit_Bars", "🎨 Edit Bars" },
            { "Edit_Mode", "Edit Mode:" },
            { "Edit_bar_colors_and_patterns", "Edit bar colors and patterns" },
            { "Element_Breakdown", "Element Breakdown" },
            { "Email", "Email:" },
            { "Enable_Axis_Break", "Enable Axis Break" },
            { "End_Type", "End Type" },
            { "End_Type_Filter", "End Type Filter:" },
            { "Ends_with", "+ Ends with" },
            { "Ensembl_ID", "Ensembl ID" },
            { "Enter_a_gene_and_click_Analyze_to_find_co_ex", "Enter a gene and click Analyze to find co-expressed genes." },
            { "Enter_a_sequence_and_click_Analyze", "Enter a sequence and click Analyze" },
            { "Enter_gene_symbol_ACTB_Ensembl_ID_ENSG000000", "Enter gene symbol (ACTB), Ensembl ID (ENSG00000075624), or NCBI Gene ID (60)" },
            { "Enter_values_and_click_Calculate", "Enter values and click Calculate" },
            { "Entrez_ID", "Entrez ID" },
            { "Enzyme", "Enzyme" },
            { "Enzyme_Filter", "Enzyme Filter:" },
            { "Error_Bar", "Error Bar:" },
            { "Error_Bar_Direction", "Error Bar Direction" },
            { "Error_Bars", "Error Bars" },
            { "Error_Type", "Error Type" },
            { "Exon", "Exon" },
            { "Export", "📥 Export" },
            { "Export_CSV", "📄 Export CSV" },
            { "Export_CSV_2", "Export CSV" },
            { "Export_Contour_Plot", "📷 Export Contour Plot" },
            { "Export_DPI", "Export DPI:" },
            { "Export_Dot_Plot", "📷 Export Dot Plot" },
            { "Export_Histogram", "📷 Export Histogram" },
            { "Export_PNG", "📷 Export PNG" },
            { "Export_PNG_2", "Export PNG" },
            { "Export_TIFF", "Export TIFF" },
            { "Export_to_CSV", "📋 Export to CSV" },
            { "Expression_Cutoff_Percentile", "Expression Cutoff Percentile: " },
            { "Extra_bases_before_RE_site_for_efficient_cut", "Extra bases before RE site for efficient cutting. Composition auto-adjusted to minimise GC% shift." },
            { "FDR_Threshold", "FDR Threshold:" },
            { "FLOW_CYTOMETRY", "FLOW CYTOMETRY" },
            { "FLOW_CYTOMETRY_2", "💉  FLOW CYTOMETRY" },
            { "Fetch_Gene", "🔍 Fetch Gene" },
            { "Fetch_gene_data_to_begin", "Fetch gene data to begin" },
            { "Figure_Preview", "📊  Figure Preview" },
            { "File", "File:" },
            { "Fill_Color", "Fill Color:" },
            { "Fill_Pattern", "Fill Pattern:" },
            { "Find_sgRNAs_in_CDS", "🧬 Find sgRNAs in CDS" },
            { "Find_sgRNAs_in_Sequence", "🧬 Find sgRNAs in Sequence" },
            { "Fit", "Fit" },
            { "Fit_preview_to_window_auto_re_fits_when_the_", "Fit preview to window (auto re-fits when the window is resized)" },
            { "Flanking_RE_Sites", "Flanking RE Sites" },
            { "Flip_H", "↔ Flip H" },
            { "Flip_V", "↕ Flip V" },
            { "Flip_horizontal_left_right", "Flip horizontal (left ↔ right)" },
            { "Flip_vertical_top_bottom", "Flip vertical (top ↔ bottom)" },
            { "Flow_Cytometry_Analyzer", "Flow Cytometry Analyzer" },
            { "Flow_Cytometry_Analyzer_Gating_ArcSinh_scali", "📈  Flow Cytometry Analyzer  —  Gating, ArcSinh scaling, high-performance dot plot rendering" },
            { "Fly_NCBI", "Fly (NCBI)" },
            { "Font", "Font:" },
            { "Font_size", "Font size" },
            { "Format", "Format" },
            { "Forward", "Forward (→)" },
            { "Forward_Primer", "Forward Primer" },
            { "Forward_Primer_2", "➤ Forward Primer" },
            { "Fragments", "Fragments:" },
            { "Frameshift_Analysis", "🧬 Frameshift Analysis" },
            { "Full_Name", "Full Name" },
            { "Full_Primer_Tm_including_RE_overhang", "🧪 Full Primer Tm (including RE overhang)" },
            { "Full_Tm_reflects_later_PCR_cycles_cycles_3_w", "💡 Full Tm reflects later PCR cycles (cycles 3+) when the overhang becomes double-stranded. Annealing temp should be based on gene-specific Tm (above)." },
            { "Fwd_5_3", "Fwd (5'→3')" },
            { "Fwd_5_RE", "Fwd 5' RE" },
            { "Fwd_Tm", "Fwd Tm" },
            { "Fwd_Tm_RE", "Fwd Tm+RE" },
            { "Fwd_Tm_RE_2", "Fwd Tm (+RE)" },
            { "Fwd_primer_will_start_before_region_Rev_prim", "Fwd primer will start before region; Rev primer will end after region. You can also drag-select a CDS block on the gene canvas." },
            { "GC", "GC %" },
            { "GC_2", "GC" },
            { "GC_Clamp", "GC Clamp" },
            { "GRAPHS", "GRAPHS" },
            { "GRAPHS_STATISTICS", "📊  GRAPHS & STATISTICS" },
            { "Gate_Inheritance", "🔄 Gate Inheritance" },
            { "Gate_List", "Gate List:" },
            { "Gate_Region", "Gate/Region" },
            { "Gating", "Gating" },
            { "Gel_Electrophoresis", "Gel Electrophoresis" },
            { "Gene", "Gene" },
            { "Gene_ID", "Gene ID:" },
            { "Gene_ID_2", "Gene ID" },
            { "Gene_ID_Converter", "Gene ID Converter" },
            { "Gene_ID_Converter_2", "🧬 Gene ID Converter" },
            { "Gene_ID_Converter_Cross_database_identifier", "🔄  Gene ID Converter  —  Cross-database identifier mapping" },
            { "Gene_ID_search", "Gene ID search:" },
            { "Gene_IDs_one_per_line", "Gene IDs (one per line):" },
            { "Gene_Name_ID", "Gene Name / ID" },
            { "Gene_Structure", "📊 Gene Structure" },
            { "Gene_Symbol_Alias", "Gene Symbol / Alias" },
            { "Gene_X", "Gene X:" },
            { "Gene_Y", "Gene Y:" },
            { "Gene_molecular_biology_vector_drawing_and_an", "  —  Gene/molecular biology vector drawing and annotation tool" },
            { "Generate_Heatmap", "Generate Heatmap" },
            { "Generate_Volcano_Plot", "Generate Volcano Plot" },
            { "GitHub", "GitHub:" },
            { "Global_Dilution_x", "Global Dilution (x):" },
            { "Global_Settings_Controls", "Global Settings & Controls" },
            { "Graph_Generator", "📊 Graph Generator" },
            { "Graphs_Generator", "Graphs Generator" },
            { "Graphs_Generator_Bar_charts_line_charts_with", "📉  Graphs Generator  —  Bar charts, line charts with full statistical analysis" },
            { "Greek_Letters", "Greek Letters" },
            { "Greek_Uppercase", "Greek (Uppercase)" },
            { "Grid_Lines", "Grid Lines" },
            { "HGNC_ID", "HGNC ID" },
            { "H_Shape", "H-Shape" },
            { "Hairpin", "Hairpin" },
            { "Hairpin_G", "Hairpin ΔG" },
            { "Halogen", "Halogen" },
            { "Heatmap", "🔗 Heatmap" },
            { "Hetero_Dimer", "Hetero-Dimer" },
            { "Hide", "✕ Hide" },
            { "High_Expression_Group", "🔴 High Expression Group" },
            { "High_top", "  |  High: top " },
            { "Highlight_Selected", "Highlight Selected" },
            { "Highlighted_genes", "📌 Highlighted genes: " },
            { "Histogram", "Histogram" },
            { "Histogram_Gating", "Histogram Gating" },
            { "Histogram_Settings", "Histogram Settings" },
            { "How_to_get_gb_files", "📖 How to get .gb files" },
            { "Human_HGNC", "Human (HGNC)" },
            { "ID", "ID" },
            { "If_one_primer_is_empty_auto_find_the_complem", "If one primer is empty, auto-find the complementary strand using these criteria:" },
            { "Image_Editor", "🖼  Image Editor" },
            { "Image_Editor_2", "Image Editor" },
            { "Import_Clipboard", "📋 Import Clipboard" },
            { "Import_gb_File", "📂 Import .gb File" },
            { "In_Development", "In Development" },
            { "Include_restriction_enzyme_overhangs", "Include restriction enzyme overhangs" },
            { "Individual", "Individual" },
            { "Input", "Input" },
            { "Input_DNA_Sequence", "📋 Input DNA Sequence" },
            { "Input_Gene_IDs_one_per_line_or_comma_tab_sep", "📝 Input Gene IDs (one per line, or comma/tab separated)" },
            { "Input_Type", "Input Type:" },
            { "Input_sequence_here", "Input sequence here..." },
            { "Insert", "Insert:" },
            { "Insert_2", "Insert" },
            { "Insert_Special_Symbol", "Insert Special Symbol" },
            { "Insert_Symbol", "Insert Symbol" },
            { "Insert_Symbol_2", "Insert Symbol..." },
            { "Interval", "Interval:" },
            { "Isoforms_CDS_Variants", "📋 Isoforms / CDS Variants" },
            { "Italic", "Italic" },
            { "Label_column_width", "Label column width" },
            { "Lanes", "Lanes:" },
            { "Lanthanide", "Lanthanide" },
            { "Layout_Settings", "Layout Settings" },
            { "Left", "← Left" },
            { "Len", "Len:" },
            { "Length", "Length: " },
            { "Length_0_bp", "Length: 0 bp" },
            { "Line", "📈 Line" },
            { "Line_Chart", "Line Chart" },
            { "Line_Color", "Line Color:" },
            { "Line_Color_2", "Line Color" },
            { "Line_Settings", "Line Settings" },
            { "Line_Style", "Line Style:" },
            { "Line_Thickness", "Line Thickness:" },
            { "Line_Thickness_2", "Line Thickness" },
            { "Line_Width", "Line Width:" },
            { "Linear", "Linear" },
            { "Linear_2", "(Linear)" },
            { "Linear_Regression", "📈 Linear Regression" },
            { "Lines", "Lines:" },
            { "Load_Data", "Load Data" },
            { "Load_FCS", "📂 Load FCS" },
            { "Load_File", "📂 Load File" },
            { "Load_Image_File", "📂  Load Image File…" },
            { "Load_Sample_Data", "📋 Load Sample Data" },
            { "Load_Selected_Vector", "📥 Load Selected Vector" },
            { "Load_built_in_4_color_demo_FCS_file_FITC_PE", "Load built-in 4-color demo FCS file (FITC / PE / PE-Cy5 / APC)" },
            { "Load_sample_data_for_current_chart_type", "Load sample data for current chart type" },
            { "Loading", "Loading..." },
            { "Log2_FC", "Log2 FC" },
            { "Log2_FC_Threshold", "Log2 FC Threshold:" },
            { "Log_Scale", "Log Scale" },
            { "Logarithmic_Scale_Log10", "Logarithmic Scale (Log10)" },
            { "Low_Expression_Group", "🔵 Low Expression Group" },
            { "Low_bottom", " , Low: bottom " },
            { "Lower_only", "Lower only" },
            { "M_W_Calculator", "M.W. Calculator" },
            { "M_W_g_mol", "M.W. (g/mol):" },
            { "Main_Scale_Major_Ticks", "Main Scale (Major Ticks)" },
            { "Main_Title", "Main Title:" },
            { "Manual_Analyze_find_complement", "Manual — Analyze / find complement" },
            { "Marker", "Marker" },
            { "Marker_Shape", "Marker Shape:" },
            { "Marker_Size", "Marker Size:" },
            { "Marker_Type", "Marker Type:" },
            { "Mass", "Mass:" },
            { "Math_Symbols", "Math Symbols" },
            { "Max", "Max" },
            { "Max_2", "Max:" },
            { "Max_Length", "Max Length" },
            { "Max_Product_bp", "Max Product (bp)" },
            { "Max_Tm_C", "Max ΔTm (°C)" },
            { "Max_Tm_C_2", "Max Tm (°C)" },
            { "Maximum", "Maximum:" },
            { "Mean_SD_SEM_Min_Max_Median_for_each_series", "Mean, SD, SEM, Min, Max, Median for each series" },
            { "Metalloid", "Metalloid" },
            { "Mg_mM", "Mg²⁺ (mM)" },
            { "Min", "Min" },
            { "Min_2", "Min:" },
            { "Min_Length", "Min Length" },
            { "Min_Product_bp", "Min Product (bp)" },
            { "Min_Tm_C", "Min Tm (°C)" },
            { "Min_r", "Min |r|:" },
            { "Minimum", "Minimum:" },
            { "Mode", "Mode:" },
            { "Molecular_Weight", "Molecular Weight" },
            { "Molecular_Weight_Calculator", "Molecular Weight Calculator" },
            { "Molecular_Weight_Calculator_2", "⚖️ Molecular Weight Calculator" },
            { "Molecular_Weight_Calculator_Peptide_and_comp", "⚖️  Molecular Weight Calculator  —  Peptide and compound MW computation" },
            { "Monovalent_cation_concentration_mM", "Monovalent cation concentration (mM)" },
            { "Mouse_NCBI", "Mouse (NCBI)" },
            { "Multi_Factors", "📊  Multi Factors" },
            { "Multi_Factors_2", "📊 Multi Factors" },
            { "Multi_Factors_Bar_Chart", "Multi Factors Bar Chart" },
            { "Multi_Select", "Multi Select" },
            { "Multiple_Matches", "ℹ️ Multiple Matches" },
            { "Multiple_cuts_2", "Multiple cuts (2+)" },
            { "N0_auto", "(0 = auto)" },
            { "N0_bp", "0 bp" },
            { "N0_genes", "0 genes" },
            { "N0_genes_2", " (0 genes)" },
            { "N1_Samples_Input_OD_Values", "1. Samples Input (OD Values)" },
            { "N1_ins", "+1 ins" },
            { "N2025_BioXAK_All_rights_reserved", "© 2025 BioXAK. All rights reserved." },
            { "N2D_Scatter_Plot", "2D Scatter Plot" },
            { "N2_Standard_Curve", "2. Standard Curve" },
            { "N2_ins", "+2 ins" },
            { "N3_Enzyme", "3' Enzyme" },
            { "N3_RE", "3' RE:" },
            { "N3_Recipe_Calculation_Result", "3. Recipe (Calculation Result)" },
            { "N3_overhang", "3' overhang" },
            { "N4_cutter", "4-cutter" },
            { "N5_Enzyme", "5' Enzyme" },
            { "N5_RE", "5' RE:" },
            { "N5_overhang", "5' overhang" },
            { "N6_cutter", "6-cutter" },
            { "N8_cutter", "8-cutter" },
            { "N95_Confidence_Interval_95_CI", "95% Confidence Interval (95% CI)" },
            { "Na_mM", "Na⁺ (mM)" },
            { "Name", "Name:" },
            { "New_Analysis", "← New Analysis" },
            { "Next", "Next →" },
            { "Next_Ctrl_N", "Next ▶ (Ctrl+N)" },
            { "Next_sample", "Next sample" },
            { "No_SPILLOVER_data_in_FCS_file", "⚠️ No $SPILLOVER data in FCS file." },
            { "No_constraint_set", "No constraint set" },
            { "No_cuts_0", "No cuts (0)" },
            { "No_file_loaded", "No file loaded" },
            { "No_local_TCGA_data_detected_Click_Start_Down", "No local TCGA data detected. Click \"Start Download\" to automatically download all cancer datasets (~3–5 GB) from Zenodo. All analysis features will be available once the download is complete." },
            { "No_region_selected", "No region selected" },
            { "No_template_loaded", "No template loaded" },
            { "Noble_Gas", "Noble Gas" },
            { "Nonmetal", "Nonmetal" },
            { "Normal_Mean", "Normal Mean" },
            { "Normal_N", "Normal N" },
            { "Normal_Only", "Normal Only" },
            { "Normal_SD", "Normal SD" },
            { "Not_Found", "⚠️ Not Found" },
            { "NucleotideComplementary", "NucleotideComplementary" },
            { "Nucleotide_Complementary", "Nucleotide Complementary" },
            { "Nucleotide_Complementary_Complement_and_reve", "🔁  Nucleotide Complementary  —  Complement and reverse complement sequences" },
            { "Number", "Number:" },
            { "Number_of_lanes", "Number of lanes:" },
            { "OD_1", "OD 1" },
            { "OD_2", "OD 2" },
            { "OD_Absorbance", "OD Absorbance" },
            { "OK", "OK" },
            { "ONGOING_PROJECTS", "🚧  ONGOING PROJECTS" },
            { "OR_enter_accession", "── OR enter accession ──" },
            { "One_Way_ANOVA_Same_Series", "📐 One-Way ANOVA (Same Series)" },
            { "One_Way_ANOVA_Same_X", "📐 One-Way ANOVA (Same X)" },
            { "Open_GitHub_repository_in_browser", "Open GitHub repository in browser" },
            { "Open_NCBI_Primer_BLAST_with_current_primers", "Open NCBI Primer-BLAST with current primers pre-filled" },
            { "Open_in_Scatter_Plot", "Open in Scatter Plot" },
            { "Open_saved_WB_layout_Ctrl_O", "Open saved WB layout (Ctrl+O)" },
            { "Open_saved_analysis_Ctrl_O", "Open saved analysis (Ctrl+O)" },
            { "Open_saved_graph_data_Ctrl_O", "Open saved graph data (Ctrl+O)" },
            { "Open_xak", "📂 Open .xak" },
            { "Orientation", "Orientation:" },
            { "Other", "Other" },
            { "Overlay", "Overlay" },
            { "PAM", "PAM:" },
            { "PAM_2", "PAM" },
            { "PROTEIN", "PROTEIN" },
            { "PROTEIN_CHEMISTRY", "🧪  PROTEIN & CHEMISTRY" },
            { "P_value_ascending", "P-value (ascending)" },
            { "Page1", "Page1" },
            { "Palindromic", "Palindromic" },
            { "Panel_1", "Panel 1" },
            { "Parameter", "Parameter:" },
            { "Parameter_s", "Parameter(s)" },
            { "Parent", "Parent" },
            { "Parent_Gate_filter_events", "Parent Gate (filter events):" },
            { "Paste", "📋 Paste" },
            { "Paste_2", "Paste" },
            { "Paste_CDS_mRNA_sequence_FASTA_or_plain", "Paste CDS/mRNA sequence (FASTA or plain)" },
            { "Paste_DNA_template_sequence_ATGC", "Paste DNA template sequence (ATGC)..." },
            { "Paste_Support_Click_any_cell_e_g_OD1_and_Ctr", "Paste Support: Click any cell (e.g., OD1) and Ctrl+V" },
            { "Paste_Transposed", "Paste Transposed" },
            { "Pearson_r", "Pearson r" },
            { "Penalize_self_complementarity_G_5_kcal_mol", "Penalize self-complementarity (ΔG < -5 kcal/mol)" },
            { "Plot", "Plot" },
            { "Plot_Type_Colors", "Plot Type & Colors" },
            { "Point_Size", "Point Size:" },
            { "Polygon", "Polygon" },
            { "Polynomial_Degree", "Polynomial Degree:" },
            { "Pos", "Pos:" },
            { "Position", "Position" },
            { "Post_transition", "Post-transition" },
            { "Preset_sizes", "Preset sizes" },
            { "Prev_Ctrl_P", "◀ Prev (Ctrl+P)" },
            { "Preview", "Preview" },
            { "Preview_2", "Preview:" },
            { "Preview_Text", "Preview Text" },
            { "Preview_top_result", "Preview (top result):" },
            { "Previous_sample", "Previous sample" },
            { "Primer_BLAST_NCBI", "🔬 Primer-BLAST (NCBI)" },
            { "Primer_Binding_Visualization", "📋 Primer Binding Visualization" },
            { "Primer_Design", "Primer Design" },
            { "Primer_Designer", "Primer Designer" },
            { "Primer_Designer_2", "🧬 Primer Designer" },
            { "Primer_Pair_Summary", "🔗 Primer Pair Summary" },
            { "Primer_Sequences_5_3", "Primer Sequences (5'→3')" },
            { "Primer_concentration_nM", "Primer concentration (nM)" },
            { "Primer_nM", "Primer (nM)" },
            { "Product", "Product" },
            { "Product_must_span_selected_region", "Product must span selected region" },
            { "Product_tolerance_bp", "Product tolerance (±bp)" },
            { "Protective_bases", "Protective bases:" },
            { "Protein", "Protein" },
            { "Protein_BCA_Calculator", "Protein BCA Calculator" },
            { "Protein_truncation_with_1_nucleotide_inserti", "Protein truncation with +1 nucleotide insertion" },
            { "Protein_truncation_with_2_nucleotide_inserti", "Protein truncation with +2 nucleotide insertion" },
            { "Quadrant", "Quadrant" },
            { "RESTRICTION_DIGEST", "✂️ RESTRICTION DIGEST" },
            { "RESTRICTION_ENZYME", "RESTRICTION ENZYME" },
            { "RESTRICTION_ENZYME_2", "🧫  RESTRICTION ENZYME" },
            { "RE_Cutting_Site_Detector", "RE Cutting Site Detector" },
            { "RE_Pattern_Predictor", "RE Pattern Predictor" },
            { "RE_Pattern_Predictor_Restriction_site_detect", "🔍  RE Pattern Predictor  —  Restriction site detection and pattern analysis" },
            { "RE_Predictor", "RE Predictor" },
            { "RE_Predictor_Enzyme_based_digestion_predicti", "🗺️  RE Predictor  —  Enzyme-based digestion prediction" },
            { "RNA", "RNA" },
            { "R_Pearson_correlation_slope_significance_for", "R², Pearson correlation, slope significance for each series" },
            { "Range_Gate", "Range Gate" },
            { "Rat_NCBI", "Rat (NCBI)" },
            { "Reaction_Conditions", "🧪 Reaction Conditions" },
            { "Ready_Load_an_FCS_file_or_demo_data_to_begin", "Ready. Load an FCS file or demo data to begin." },
            { "Ready_to_download", "Ready to download..." },
            { "Recently_Used", "Recently Used" },
            { "Recognition", "Recognition" },
            { "Recommended", "⭐ = Recommended" },
            { "Recommended_criteria", "Recommended criteria:" },
            { "Record_Ctrl_M", "📊 Record (Ctrl+M)" },
            { "Record_current_gating_statistics_to_table", "Record current gating statistics to table" },
            { "Refresh_Preview", "Refresh Preview" },
            { "Regression_Trendline", "Regression / Trendline" },
            { "Regulation", "Regulation" },
            { "Remove", "✕ Remove" },
            { "Remove_Panel", "➖ Remove Panel" },
            { "Replicates", "Replicates:" },
            { "Require_GC_clamp_3_G_or_C", "Require GC clamp (3' G or C)" },
            { "Reset", "Reset" },
            { "Reset_2", "↺ Reset" },
            { "Reset_All", "Reset All" },
            { "Reset_Compensation", "↺ Reset Compensation" },
            { "Reset_Range", "Reset Range" },
            { "Reset_Zoom", "Reset Zoom" },
            { "Reset_crop_selection_to_full_image", "Reset crop selection to full image" },
            { "Restriction_Enzyme_Pattern_Predictor", "Restriction Enzyme Pattern Predictor" },
            { "Restriction_Enzyme_Predictor", "Restriction Enzyme Predictor" },
            { "Results", "Results: " },
            { "Results_2", "Results" },
            { "Rev_5_3", "Rev (5'→3')" },
            { "Rev_5_RE", "Rev 5' RE" },
            { "Rev_Tm", "Rev Tm" },
            { "Rev_Tm_RE", "Rev Tm+RE" },
            { "Rev_Tm_RE_2", "Rev Tm (+RE)" },
            { "Reverse", "Reverse" },
            { "Reverse_2", "Reverse (←)" },
            { "Reverse_Complement", "Reverse Complement" },
            { "Reverse_Primer", "◄ Reverse Primer" },
            { "Reverse_Primer_enter_as_5_3", "Reverse Primer (enter as 5'→3')" },
            { "Reverse_strand", "Reverse strand" },
            { "Right", "→ Right" },
            { "Rotate_90_clockwise", "Rotate 90° clockwise" },
            { "Rotate_90_counter_clockwise", "Rotate 90° counter-clockwise" },
            { "Rotation_Flip", "Rotation & Flip" },
            { "Row_spacing", "Row spacing" },
            { "Run_Analysis", "Run Analysis" },
            { "Same_Series", "Same Series" },
            { "Same_X_Row", "Same X (Row)" },
            { "Sample", "Sample" },
            { "Sample_Condition", "🔬 Sample Condition:" },
            { "Sample_L", "Sample (µL)" },
            { "Save_PNG", "💾 Save PNG" },
            { "Save_SVG", "💾 Save SVG" },
            { "Save_WB_layout_Ctrl_S", "Save WB layout (Ctrl+S)" },
            { "Save_analysis_state_Ctrl_S", "Save analysis state (Ctrl+S)" },
            { "Save_current_graph_data_Ctrl_S", "Save current graph data (Ctrl+S)" },
            { "Save_xak", "💾 Save .xak" },
            { "Scale", "Scale:" },
            { "Scale_2", "Scale" },
            { "Scatter", "📈 Scatter" },
            { "Scatter_2", "⚬ Scatter" },
            { "Scatter_Plot", "Scatter Plot" },
            { "Score", "Score" },
            { "Search", "🔍 Search:" },
            { "Search_Gene", "🔍 Search Gene:" },
            { "Search_Gene_2", "🔍 Search Gene" },
            { "Search_Gene_from_NCBI", "🔍 Search Gene from NCBI" },
            { "Search_enzyme", "Search enzyme..." },
            { "Search_enzyme_2", "  🔍 Search enzyme..." },
            { "Select_All", "Select All" },
            { "Select_All_Deselect_All", "Select All / Deselect All" },
            { "Select_Enzyme", "Select Enzyme:" },
            { "Select_Error_Bar_Type", "Select Error Bar Type" },
            { "Select_a_Color", "Select a Color" },
            { "Select_a_construct", "Select a construct" },
            { "Select_cells_and_Ctrl_C_to_copy_or_right_cli", "💡 Select cells and Ctrl+C to copy, or right-click for options" },
            { "Select_species_to_download_from_HGNC_NCBI", "Select species to download from HGNC/NCBI:" },
            { "Selected", "Selected: " },
            { "Selected_Cancers", "Selected Cancers" },
            { "Selected_Enzyme", "Selected Enzyme:" },
            { "Selected_Region", "Selected Region:" },
            { "Self_Comp", "Self-Comp" },
            { "Self_Dimer_G", "Self-Dimer ΔG" },
            { "Sequence", "Sequence" },
            { "Sequence_Type", "Sequence Type" },
            { "Series", "Series:" },
            { "Series_Settings", "Series Settings" },
            { "Set_Bounds", "↔ Set Bounds" },
            { "Set_Lanes", "● Set Lanes" },
            { "Set_constraint_to_the_full_CDS_region", "Set constraint to the full CDS region" },
            { "Set_from_CDS", "🧬 Set from CDS" },
            { "Set_from_canvas_selection", "📌 Set from canvas selection" },
            { "Set_official_symbol_as_antibody_name", "Set official symbol as antibody name" },
            { "Settings_auto_apply_on_click_outside", "⚡ Settings auto-apply on click outside" },
            { "Setup_Channels", "⚙️ Setup Channels…" },
            { "Show_Border", "Show Border" },
            { "Show_Grid_Lines_at_major_ticks", "Show Grid Lines (at major ticks)" },
            { "Show_enzymes_with", "Show enzymes with:" },
            { "Show_equation_R_on_chart", "Show equation & R² on chart" },
            { "Show_individual_data_points_on_bars", "Show individual data points on bars" },
            { "Show_minor_ticks", "Show minor ticks" },
            { "Show_regression_line", "Show regression line" },
            { "Side_Labels", "Side Labels" },
            { "Significant_Genes", "📋 Significant Genes" },
            { "Single", "Single" },
            { "Single_Select", "Single Select" },
            { "Single_cut_1", "Single cut (1)" },
            { "Size", "Size:" },
            { "Size_bp", "Size (bp)" },
            { "Skip_for_Now", "Skip for Now" },
            { "Some_events_with_0_values_are_excluded_from", "⚠️ Some events with ≤0 values are excluded from Log scale display." },
            { "Sort_Asc", "↑ Sort Asc" },
            { "Sort_Desc", "↓ Sort Desc" },
            { "Sort_by", "Sort by:" },
            { "Species", "Species:" },
            { "Species_2", "Species" },
            { "Standard_Deviation_SD", "Standard Deviation (SD)" },
            { "Standard_Error_of_Mean_SEM", "Standard Error of Mean (SEM)" },
            { "Start_Download", "▶  Start Download" },
            { "Starts_with", "Starts with" },
            { "Statistical_Analysis", "Statistical Analysis" },
            { "Statistical_Analysis_2", "📊 Statistical Analysis" },
            { "Statistics", "📊 Statistics" },
            { "Statistics_Table", "📋 Statistics Table" },
            { "Status", "Status" },
            { "Step_1_Select_Statistical_Method", "Step 1: Select Statistical Method" },
            { "Step_2_Configure_Analysis", "Step 2: Configure Analysis" },
            { "Straight_Line", "Straight Line" },
            { "Style", "Style:" },
            { "Sub_Scale_Minor_Ticks", "Sub Scale (Minor Ticks)" },
            { "Subscript_Superscript", "Subscript/Superscript" },
            { "Subtitle", "Subtitle:" },
            { "Survival_KM", "📉 Survival (KM)" },
            { "Symbol", "Symbol" },
            { "Symbol_2", "Ω Symbol" },
            { "TCGA_Analysis", "TCGA Analysis" },
            { "TCGA_Analysis_Box_plots_heatmaps_scatter_plo", "📊  TCGA Analysis  —  Box plots, heatmaps, scatter plots, Kaplan-Meier survival, volcano plots" },
            { "TCGA_DATABASE", "TCGA DATABASE" },
            { "TCGA_DATABASE_2", "🧬  TCGA DATABASE" },
            { "TCGA_Database_Analysis", "TCGA Database Analysis" },
            { "TCGA_Database_Initialization", "🧬  TCGA Database Initialization" },
            { "TP53", "TP53" },
            { "T_Test_Two_Groups", "🔬 T-Test (Two Groups)" },
            { "Target_Gene", "Target Gene:" },
            { "Target_Product_bp", "Target Product (bp)" },
            { "Target_Tm_C", "Target Tm (°C)" },
            { "Target_g", "Target (µg):" },
            { "Text", "📝 Text" },
            { "Text_Annotation", "Text Annotation" },
            { "Text_Content", "Text Content" },
            { "Threshold", "Threshold" },
            { "Tick_Marks", "Tick Marks" },
            { "Tip_Select_cells_and_press_Ctrl_C_to_copy_or", "💡 Tip: Select cells and press Ctrl+C to copy, or use the Copy Results button to copy all" },
            { "Tip_Select_start_cell_to_paste", "Tip: Select start cell to paste" },
            { "Tip_You_can_change_direction_for_individual", "Tip: You can change direction for individual bars by right-clicking on them." },
            { "Title", "Title:" },
            { "Titles", "Titles" },
            { "Tm", "ΔTm" },
            { "Tm_C", "Tm (°C)" },
            { "Tm_Owczarzy_2008_SantaLucia_1998_NN", "Tm: Owczarzy 2008 + SantaLucia 1998 NN" },
            { "Tm_full", "ΔTm (full)" },
            { "Tm_tolerance_C", "Tm tolerance (±°C)" },
            { "Top_Group_Labels", "Top Group Labels" },
            { "Topology", "Topology:" },
            { "Total_Vol_L", "Total Vol (µL):" },
            { "Transition", "Transition" },
            { "Treats_entire_sequence_as_one_exon_for_sgRNA", "Treats entire sequence as one exon for sgRNA design" },
            { "Tumor_Mean", "Tumor Mean" },
            { "Tumor_N", "Tumor N" },
            { "Tumor_Only", "Tumor Only" },
            { "Tumor_SD", "Tumor SD" },
            { "Two_Way_ANOVA", "📊 Two-Way ANOVA" },
            { "Type", "Type:" },
            { "U_Shape", "U-Shape (ㄇ)" },
            { "Undo", "↩ Undo" },
            { "Up", "↑ Up" },
            { "Update_Database", "🔄 Update Database" },
            { "Upper_only", "Upper only" },
            { "Use", "Use" },
            { "Use_Entire_Sequence", "Use Entire Sequence" },
            { "Use_Selected_Region", "Use Selected Region" },
            { "Use_This_Sequence", "Use This Sequence" },
            { "Use_in_Main_Title_for_two_lines", "(Use | in Main Title for two lines)" },
            { "Use_the_region_you_dragged_on_the_gene_visua", "Use the region you dragged on the gene visualization canvas" },
            { "VECTOR_LIBRARY", "VECTOR LIBRARY" },
            { "Vector", "Vector:" },
            { "Vector_Design", "Vector Design" },
            { "Vector_Designer", "Vector Designer" },
            { "Vector_Designer_2", "🧬 Vector Designer" },
            { "Version_1_0_0", "Version 1.0.0" },
            { "Version_Loading", "Version: Loading..." },
            { "View", "View" },
            { "View_Type", "View Type" },
            { "Volcano", "🌋 Volcano" },
            { "Volcano_Plot", "Volcano Plot" },
            { "Volume", "Volume:" },
            { "WB_Organizer", "WB Organizer" },
            { "WESTERN_BLOT", "WESTERN BLOT" },
            { "WORKSPACE", "WORKSPACE" },
            { "Water_L", "Water (µL)" },
            { "Western_Blot_Organizer", "Western Blot Organizer" },
            { "Worm_NCBI", "Worm (NCBI)" },
            { "X_Axis", "X Axis" },
            { "X_Axis_Parameter", "X Axis Parameter:" },
            { "X_Axis_Settings", "X Axis Settings" },
            { "X_Axis_Title", "X Axis Title:" },
            { "X_Column", "X Column" },
            { "X_Index", "X Index:" },
            { "X_Range", "X Range:" },
            { "X_Scale", "X Scale:" },
            { "X_Y_Graph", "📈  X-Y Graph" },
            { "Y_Axis", "Y Axis" },
            { "Y_Axis_Parameter", "Y Axis Parameter:" },
            { "Y_Axis_Settings", "Y Axis Settings" },
            { "Y_Axis_Title", "Y Axis Title:" },
            { "Y_Columns", "Y Columns" },
            { "Y_Data_Mode", "Y Data Mode" },
            { "Y_Range", "Y Range:" },
            { "Y_Scale", "Y Scale:" },
            { "Zebrafish_NCBI", "Zebrafish (NCBI)" },
            { "Zoom", "Zoom:" },
            { "Zoom_In", "Zoom In" },
            { "Zoom_Out", "Zoom Out" },
            { "before_PAM_GC_content", "(before PAM) + GC content" },
            { "bowtobyd_gmail_com", "bowtobyd@gmail.com" },
            { "dNTP_concentration_mM", "dNTP concentration (mM)" },
            { "dNTP_mM", "dNTP (mM)" },
            { "data_spread", " - data spread" },
            { "github_com_bowyung_BioXAK", "github.com/bowyung/BioXAK" },
            { "per_major_tick", "per major tick" },
            { "precision", " - precision" },
            { "pt", "pt" },
            { "px", "px" },
            { "r_descending", "|r| (descending)" },
            { "r_descending_2", "r (descending)" },
            { "sgRNA", "sgRNA" },
            { "sgRNA_Candidates", "🎯 sgRNA Candidates" },
            { "sgRNA_Designer", "sgRNA Designer" },
            { "sgRNA_Designer_Guide_RNA_design_with_gene_st", "🔬  sgRNA Designer  —  Guide RNA design with gene structure visualization and frameshift analysis" },
            { "sgRNA_Sequence_5_3", "sgRNA Sequence (5'→3')" },
            { "y_ax_b", "y = ax + b" },
        };

        public static readonly Dictionary<string, string> ZhHant = new Dictionary<string, string>
        {
            { "ADD_CUSTOM_SEQUENCE", "新增自訂序列" },
            { "About", "關於" },
            { "About_BioXAK", "關於 BioXAK" },
            { "Accepts_Symbol_ENSG_ID_NCBI_ID", "可接受：Symbol、ENSG ID、NCBI ID" },
            { "Accession_NM_NG_NR", "Accession (NM_ / NG_ / NR_)" },
            { "Actinide", "錒系元素" },
            { "Active_Template_Sequence", "目前使用的模板序列" },
            { "Add", "+ 新增" },
            { "Add_2", "新增：" },
            { "Add_Feature", "新增註解" },
            { "Add_Label", "+ 新增標籤" },
            { "Add_Label_2", "▶ 新增標籤" },
            { "Add_Panel", "➕ 新增面板" },
            { "Add_Row", "+ 新增列" },
            { "Add_Sequence", "➕ 新增序列" },
            { "Add_Text_Box", "新增文字方塊" },
            { "Add_restriction_enzyme_overhangs", "加入限制酶黏端序列" },
            { "Add_to_Blot_Images", "➕  加入 Blot 影像清單" },
            { "Adjust_then_add_to_Blot_Images", "調整後再加入 Blot 影像清單" },
            { "Alkali", "鹼金屬" },
            { "Alkaline_Earth", "鹼土金屬" },
            { "All_Bars", "所有長條" },
            { "Analysis_Parameters_Guide", "📘 分析參數說明" },
            { "Analyze", "分析" },
            { "Analyze_All_Enzymes", "分析所有限制酶" },
            { "Analyze_Co_Expression", "分析共表現" },
            { "Analyze_Find_Complement", "分析／尋找互補股" },
            { "Analyze_effects_of_Series_and_X_value_requir", "分析數列與 X 值的效應 (需多列資料)" },
            { "Analyze_protein_truncation_caused_by_1_2_fra", "分析 Cas9 切割後 +1/+2 框移所造成的蛋白質截斷" },
            { "Angle", "角度" },
            { "Antibody_name", "抗體名稱：" },
            { "Antibody_name_for_selected_blot", "所選 blot 的抗體名稱：" },
            { "Any_Self_Comp", "任意自身互補" },
            { "Apply", "套用" },
            { "Apply_All_Gates_to_Current_Sample", "📋 套用所有 Gate 至目前樣本" },
            { "Apply_Compensation", "套用補償" },
            { "Apply_gate_regions_to_current_sample", "將 Gate 區域套用至目前樣本：" },
            { "Arrow_Direction", "箭頭方向" },
            { "Arrows", "箭頭" },
            { "Auto", "自動" },
            { "Auto_Detect", "自動偵測" },
            { "Auto_Detect_Symbol_Ensembl_ENSG_Entrez_numbe", "💡 自動偵測：Symbol、Ensembl (ENSG…)、Entrez (數字)、HGNC (HGNC:…)" },
            { "Auto_Pick_Parameters", "自動挑選參數" },
            { "Auto_Pick_Primers", "🔍 自動挑選引子" },
            { "Auto_Pick_optimal_primer_pairs", "自動 — 挑選最佳引子對" },
            { "Auto_Picked_Primer_Pairs", "🏆 自動挑選的引子對" },
            { "Auto_Scale_round_to_nice_numbers", "自動刻度 (取整為易讀數值)" },
            { "Auto_apply_on_file_switch", "切換檔案時自動套用" },
            { "Auto_arrange_and_annotate_blot_images", "自動排版與標註 blot 影像" },
            { "Available_Cancers", "可選癌症" },
            { "Avg", "平均" },
            { "Axis_Break_Segment", "座標軸斷軸" },
            { "Axis_Range_empty_auto", "座標軸範圍 (留空 = 自動)" },
            { "Axis_Settings", "座標軸設定" },
            { "Axis_Title", "座標軸標題" },
            { "BCA_Conc_Calculator", "BCA 濃度計算器" },
            { "BCA_Concentration_Calculator_Standard_curve", "📐  BCA 濃度計算器  —  以標準曲線進行蛋白質定量" },
            { "BLAST_Selected", "🔬 對所選進行 BLAST" },
            { "Back", "← 上一步" },
            { "Bake_crop_selected_region_fills_the_preview", "套用裁切：所選區域將填滿預覽" },
            { "Bar_Chart", "長條圖" },
            { "Base", "底數：" },
            { "BioXAK_Biology_X_Analysis_Kit", "BioXAK - 生物分析工具組" },
            { "BioXAK_TCGA_Data_Initialization", "BioXAK — TCGA 資料初始化" },
            { "BioXAK_is_a_comprehensive_bioinformatics_too", "BioXAK 是為生命科學研究者打造的整合式生物資訊工具組——單一桌面平台即可涵蓋癌症基因體學、CRISPR 設計、流式細胞術、序列分析與實驗室計算。" },
            { "Biology_X_Analysis_Kit", "生物分析工具組" },
            { "Biotype", "基因類型" },
            { "Blot_Images", "Blot 影像" },
            { "Blot_display_width", "Blot 顯示寬度" },
            { "Blunt", "平端" },
            { "Bold", "粗體" },
            { "Border", "邊框：" },
            { "Border_0_5_mm_Height_scales_proportionally", "邊框 = 0.5 mm  |  高度依比例縮放" },
            { "Border_Color", "邊框顏色：" },
            { "Border_Width", "邊框寬度：" },
            { "Both", "↔ 雙向" },
            { "Box_Plot", "📊 盒鬚圖" },
            { "Break_End", "斷軸終點：" },
            { "Break_Start", "斷軸起點：" },
            { "Brightness_Levels", "亮度階調" },
            { "Buffer", "緩衝液：" },
            { "Buffer_L", "緩衝液 (µL)" },
            { "CALCULATE_ALL", "全部計算" },
            { "CHEMICAL", "化學" },
            { "CLONING", "選殖" },
            { "CLONING_2", "🔬 選殖" },
            { "CONTACT", "📬  聯絡方式" },
            { "CRISPR_GENE_EDITING", "CRISPR / 基因編輯" },
            { "CRISPR_GENE_EDITING_2", "✂️  CRISPR / 基因編輯" },
            { "Calculate", "計算" },
            { "Cancel", "取消" },
            { "Cancer", "癌症" },
            { "Cancer_Type_Selection", "📊 癌症類型選擇" },
            { "Chart", "圖表" },
            { "Chart_Settings", "圖表設定" },
            { "Chart_Title", "圖表標題：" },
            { "Chart_Type", "圖表類型" },
            { "Chart_height_px", "圖表高度 (px)" },
            { "Chart_width_px", "圖表寬度 (px)" },
            { "Chemical_Formula", "化學式" },
            { "Choose", "選擇…" },
            { "Choose_Color", "選擇顏色" },
            { "Choose_Color_2", "選擇顏色…" },
            { "Circular", "環狀" },
            { "Circular_Linear", "環狀／線狀" },
            { "Clear", "清除" },
            { "Clear_2", "🗑️ 清除" },
            { "Clear_3", "✕ 清除" },
            { "Clear_All", "🗑️ 全部清除" },
            { "Clear_All_2", "全部清除" },
            { "Clear_All_3", "🗑 全部清除" },
            { "Clear_All_Gates", "🗑️ 清除所有 Gate" },
            { "Clear_All_Highlights", "清除所有標示" },
            { "Click_Find_sgRNAs_in_CDS_after_loading_gene", "載入基因後請點擊「在 CDS 中尋找 sgRNA」" },
            { "Click_and_drag_on_the_gene_map_above_to_sele", "💡 在上方基因圖譜上拖曳，即可選取一段區域作為引子設計模板。" },
            { "Click_for_explanation", "點擊查看說明" },
            { "Click_on_preview_to_place_a_side_label_line", "在預覽區點擊即可放置側邊標籤線" },
            { "Click_set_Left_then_Right_boundary_alternate", "點擊：依序設定左、右邊界 (交替)。右鍵：移除最近的一個。" },
            { "Click_to_add_vertices_double_click_to_comple", "💡 點擊以新增頂點，雙擊完成多邊形 (至少 3 點)" },
            { "Click_to_copy_email_address", "點擊以複製電子郵件地址" },
            { "Click_to_expand_collapse", "點擊以展開／收合" },
            { "Click_to_place_lane_center_Right_click_to_re", "點擊以放置泳道中心；按右鍵可移除。" },
            { "Click_to_preview_primer_details_below", "💡 點擊即可在下方預覽引子詳細資訊。" },
            { "Click_to_show_above_below_percentages", "💡 點擊以顯示閾值上／下的百分比" },
            { "Clone", "📋 複製" },
            { "Clone_Insert_into_Vector", "🧬 將片段選殖入載體" },
            { "Close", "關閉" },
            { "Co_Expression", "🔗 共表現分析" },
            { "Color", "顏色：" },
            { "Column", "📊  直條" },
            { "Column_2", "📊 直條" },
            { "Column_Chart", "直條圖" },
            { "Coming_soon", "敬請期待！" },
            { "Compare_different_X_values_within_one_series", "比較同一數列中不同 X 值之間的差異" },
            { "Compare_multiple_series_at_a_specific_X_valu", "比較多個數列在特定 X 值下的差異" },
            { "Compare_two_series_at_a_specific_X_value_usi", "以重複資料比較兩個數列在特定 X 值下的差異" },
            { "Compares_Tumor_vs_Normal", "  (比較腫瘤 vs 正常)" },
            { "Compensation", "螢光補償" },
            { "Complement", "互補" },
            { "Conc", "濃度" },
            { "Conc_g_L", "濃度 (µg/µL)" },
            { "Conc_ng_L", "濃度 (ng/µL)" },
            { "Concentration", "濃度：" },
            { "Concentration_Calculator", "濃度計算器" },
            { "Concentration_Calculator_Molar_concentration", "🧫  濃度計算器  —  莫耳濃度與稀釋工具" },
            { "Condition_Labels", "條件標籤" },
            { "Condition_rows", "條件列數：" },
            { "Conditions_for_missing_strand", "缺少該股時的搜尋條件" },
            { "Connect_scatter_points_with_lines", "以線條連接散佈點" },
            { "Connecting", "連線中…" },
            { "Contour_Colormap", "等高線色階：" },
            { "Contour_Plot", "等高線圖" },
            { "Conversion_Results", "📊 轉換結果" },
            { "Convert", "🔄 轉換" },
            { "Convert_to_Grayscale", "轉為灰階" },
            { "Copy", "複製" },
            { "Copy_2", "📋 複製" },
            { "Copy_All", "📋 全部複製" },
            { "Copy_All_2", "全部複製" },
            { "Copy_Cell_s", "複製儲存格" },
            { "Copy_Column", "複製整欄" },
            { "Copy_Eq", "📋 複製方程式" },
            { "Copy_Not_Found_IDs", "📋 複製找不到的 ID" },
            { "Copy_R", "📋 複製 R²" },
            { "Copy_Recipe_Table", "複製配方表" },
            { "Copy_Results", "📋 複製結果" },
            { "Copy_Row_s", "複製整列" },
            { "Copy_Sequence", "📋 複製序列" },
            { "Copy_Stats", "📋 複製統計" },
            { "Copy_Table", "📋 複製表格" },
            { "Copy_to_Clipboard", "📄 複製到剪貼簿" },
            { "Copy_to_Clipboard_2", "📋 複製到剪貼簿" },
            { "Count", "數量" },
            { "Crop", "✂ 裁切" },
            { "Custom_Color_RGB", "自訂顏色 (RGB)" },
            { "Cut_Positions", "切割位置" },
            { "Cut_sites_select_or_auto_detect", "切位 (手動選擇或自動偵測)：" },
            { "Cuts", "切割次數" },
            { "Cycle_fill_pattern", "循環填色樣式" },
            { "DNA_Sequence", "DNA 序列：" },
            { "DNA_TOOLS", "DNA 工具" },
            { "DNA_TOOLS_2", "🔤  DNA 工具" },
            { "Data_Points", "資料點" },
            { "Data_source_HGNC_Human_NCBI_Gene_Other_speci", "資料來源：HGNC (人類)、NCBI Gene (其他物種)" },
            { "Database_Information", "ℹ️ 資料庫資訊" },
            { "Delete", "🗑 刪除" },
            { "Delete_2", "刪除" },
            { "Delete_Del", "🗑 刪除 (Del)" },
            { "Delete_Selected_Row", "刪除所選列" },
            { "Demo_FCS", "🧪 範例 FCS" },
            { "Descriptive_Statistics", "📋 描述統計" },
            { "Design_Mode", "設計模式" },
            { "Details", "詳細資料" },
            { "Digest", "切割" },
            { "Digest_2", "✂️ 切割" },
            { "Digestion_Results", "切割結果：" },
            { "Direct_Sequence_Input", "📝 直接輸入序列" },
            { "Direction", "方向" },
            { "Divalent_cation_concentration_mM", "雙價陽離子濃度 (mM)" },
            { "Divisions", "分割數：" },
            { "Dot_Colormap", "點圖色階：" },
            { "Dot_Plot", "點圖" },
            { "Double_click_chart_to_edit_Ctrl_A_Select_All", "雙擊圖表可編輯 | Ctrl+A：全選 | Del：刪除" },
            { "Down", "↓ 下移" },
            { "Download_Selected", "⬇️ 下載所選" },
            { "Drag_on_map_to_view_sequence_Ready", "在圖譜上拖曳即可檢視序列。就緒。" },
            { "Edit_Bar", "編輯長條" },
            { "Edit_Bar_Style", "編輯長條樣式" },
            { "Edit_Bar_Styles", "編輯長條樣式" },
            { "Edit_Bar_Styles_2", "🎨 編輯長條樣式" },
            { "Edit_Bars", "🎨 編輯長條" },
            { "Edit_Mode", "編輯模式：" },
            { "Edit_bar_colors_and_patterns", "編輯長條的顏色與填色樣式" },
            { "Element_Breakdown", "元素組成" },
            { "Email", "電子郵件：" },
            { "Enable_Axis_Break", "啟用斷軸" },
            { "End_Type", "末端類型" },
            { "End_Type_Filter", "末端類型篩選：" },
            { "Ends_with", "+ 結尾為" },
            { "Enter_a_gene_and_click_Analyze_to_find_co_ex", "請輸入基因並按「分析」以尋找共表現基因。" },
            { "Enter_a_sequence_and_click_Analyze", "請輸入序列後按「分析」" },
            { "Enter_gene_symbol_ACTB_Ensembl_ID_ENSG000000", "輸入基因 Symbol (ACTB)、Ensembl ID (ENSG00000075624) 或 NCBI Gene ID (60)" },
            { "Enter_values_and_click_Calculate", "請輸入數值後按「計算」" },
            { "Enzyme", "限制酶" },
            { "Enzyme_Filter", "限制酶篩選：" },
            { "Error_Bar", "誤差線：" },
            { "Error_Bar_Direction", "誤差線方向" },
            { "Error_Bars", "誤差線" },
            { "Error_Type", "誤差類型" },
            { "Export", "📥 匯出" },
            { "Export_CSV", "📄 匯出 CSV" },
            { "Export_CSV_2", "匯出 CSV" },
            { "Export_Contour_Plot", "📷 匯出等高線圖" },
            { "Export_DPI", "匯出 DPI：" },
            { "Export_Dot_Plot", "📷 匯出點圖" },
            { "Export_Histogram", "📷 匯出直方圖" },
            { "Export_PNG", "📷 匯出 PNG" },
            { "Export_PNG_2", "匯出 PNG" },
            { "Export_TIFF", "匯出 TIFF" },
            { "Export_to_CSV", "📋 匯出為 CSV" },
            { "Expression_Cutoff_Percentile", "表現量分組百分位： " },
            { "Extra_bases_before_RE_site_for_efficient_cut", "在限制酶切位前加入的額外鹼基，以利切割效率。組成會自動調整以降低 GC% 偏移。" },
            { "FDR_Threshold", "FDR 閾值：" },
            { "FLOW_CYTOMETRY", "流式細胞術" },
            { "FLOW_CYTOMETRY_2", "💉  流式細胞術" },
            { "Fetch_Gene", "🔍 取得基因" },
            { "Fetch_gene_data_to_begin", "請先取得基因資料以開始" },
            { "Figure_Preview", "📊  圖片預覽" },
            { "File", "檔案：" },
            { "Fill_Color", "填滿顏色：" },
            { "Fill_Pattern", "填滿樣式：" },
            { "Find_sgRNAs_in_CDS", "🧬 在 CDS 中尋找 sgRNA" },
            { "Find_sgRNAs_in_Sequence", "🧬 在序列中尋找 sgRNA" },
            { "Fit", "符合視窗" },
            { "Fit_preview_to_window_auto_re_fits_when_the_", "縮放至符合視窗（之後視窗大小改變會自動跟著調整）" },
            { "Flanking_RE_Sites", "兩側限制酶切位" },
            { "Flip_H", "↔ 水平翻轉" },
            { "Flip_V", "↕ 垂直翻轉" },
            { "Flip_horizontal_left_right", "水平翻轉 (左 ↔ 右)" },
            { "Flip_vertical_top_bottom", "垂直翻轉 (上 ↔ 下)" },
            { "Flow_Cytometry_Analyzer", "流式細胞分析" },
            { "Flow_Cytometry_Analyzer_Gating_ArcSinh_scali", "📈  流式細胞分析  —  圈選 (Gating)、ArcSinh 座標、高效能點圖繪製" },
            { "Fly_NCBI", "果蠅 (NCBI)" },
            { "Font", "字型：" },
            { "Font_size", "字型大小" },
            { "Format", "格式" },
            { "Forward", "正向 (→)" },
            { "Forward_Primer", "正向引子" },
            { "Forward_Primer_2", "➤ 正向引子" },
            { "Fragments", "片段：" },
            { "Frameshift_Analysis", "🧬 框移分析" },
            { "Full_Name", "全名" },
            { "Full_Primer_Tm_including_RE_overhang", "🧪 完整引子 Tm (含限制酶黏端)" },
            { "Full_Tm_reflects_later_PCR_cycles_cycles_3_w", "💡 完整 Tm 反映 PCR 後期循環 (第 3 循環之後)、黏端已成雙股時的情況。退火溫度仍應以上方的基因專一性 Tm 為準。" },
            { "Fwd_5_3", "正向 (5'→3')" },
            { "Fwd_5_RE", "正向 5' 限制酶" },
            { "Fwd_Tm", "正向 Tm" },
            { "Fwd_Tm_RE", "正向 Tm+RE" },
            { "Fwd_Tm_RE_2", "正向 Tm (+RE)" },
            { "Fwd_primer_will_start_before_region_Rev_prim", "正向引子會落在區域之前起始；反向引子會落在區域之後結束。你也可以在基因畫布上拖曳選取某個 CDS 區塊。" },
            { "GC_Clamp", "GC clamp" },
            { "GRAPHS", "繪圖" },
            { "GRAPHS_STATISTICS", "📊  繪圖與統計" },
            { "Gate_Inheritance", "🔄 Gate 繼承" },
            { "Gate_List", "Gate 清單：" },
            { "Gate_Region", "Gate／區域" },
            { "Gating", "圈選 (Gating)" },
            { "Gel_Electrophoresis", "膠體電泳" },
            { "Gene", "基因" },
            { "Gene_ID", "基因 ID：" },
            { "Gene_ID_2", "基因 ID" },
            { "Gene_ID_Converter", "基因 ID 轉換器" },
            { "Gene_ID_Converter_2", "🧬 基因 ID 轉換器" },
            { "Gene_ID_Converter_Cross_database_identifier", "🔄  基因 ID 轉換器  —  跨資料庫識別碼對應" },
            { "Gene_ID_search", "基因 ID 搜尋：" },
            { "Gene_IDs_one_per_line", "基因 ID (每行一個)：" },
            { "Gene_Name_ID", "基因名稱／ID" },
            { "Gene_Structure", "📊 基因結構" },
            { "Gene_Symbol_Alias", "基因 Symbol／別名" },
            { "Gene_X", "基因 X：" },
            { "Gene_Y", "基因 Y：" },
            { "Gene_molecular_biology_vector_drawing_and_an", "  —  基因／分子生物學載體繪製與註解工具" },
            { "Generate_Heatmap", "產生熱圖" },
            { "Generate_Volcano_Plot", "產生火山圖" },
            { "GitHub", "GitHub：" },
            { "Global_Dilution_x", "整體稀釋倍數 (x)：" },
            { "Global_Settings_Controls", "整體設定與控制" },
            { "Graph_Generator", "📊 繪圖產生器" },
            { "Graphs_Generator", "繪圖產生器" },
            { "Graphs_Generator_Bar_charts_line_charts_with", "📉  繪圖產生器  —  長條圖、折線圖，並附完整統計分析" },
            { "Greek_Letters", "希臘字母" },
            { "Greek_Uppercase", "希臘字母 (大寫)" },
            { "Grid_Lines", "格線" },
            { "H_Shape", "H 形線" },
            { "Hairpin", "髮夾結構" },
            { "Hairpin_G", "髮夾 ΔG" },
            { "Halogen", "鹵素" },
            { "Heatmap", "🔗 熱圖" },
            { "Hetero_Dimer", "異源二聚體" },
            { "Hide", "✕ 隱藏" },
            { "High_Expression_Group", "🔴 高表現組" },
            { "High_top", "  |  高：前 " },
            { "Highlight_Selected", "標示所選" },
            { "Highlighted_genes", "📌 已標示基因： " },
            { "Histogram", "直方圖" },
            { "Histogram_Gating", "直方圖圈選" },
            { "Histogram_Settings", "直方圖設定" },
            { "How_to_get_gb_files", "📖 如何取得 .gb 檔" },
            { "Human_HGNC", "人類 (HGNC)" },
            { "If_one_primer_is_empty_auto_find_the_complem", "若其中一條引子留空，將依下列條件自動尋找互補股：" },
            { "Image_Editor", "🖼  影像編輯器" },
            { "Image_Editor_2", "影像編輯器" },
            { "Import_Clipboard", "📋 從剪貼簿匯入" },
            { "Import_gb_File", "📂 匯入 .gb 檔" },
            { "In_Development", "開發中" },
            { "Include_restriction_enzyme_overhangs", "納入限制酶黏端序列" },
            { "Individual", "單一長條" },
            { "Input", "輸入" },
            { "Input_DNA_Sequence", "📋 輸入 DNA 序列" },
            { "Input_Gene_IDs_one_per_line_or_comma_tab_sep", "📝 輸入基因 ID (每行一個，或以逗號／Tab 分隔)" },
            { "Input_Type", "輸入類型：" },
            { "Input_sequence_here", "在此輸入序列…" },
            { "Insert", "插入片段：" },
            { "Insert_2", "插入" },
            { "Insert_Special_Symbol", "插入特殊符號" },
            { "Insert_Symbol", "插入符號" },
            { "Insert_Symbol_2", "插入符號…" },
            { "Interval", "間隔：" },
            { "Isoforms_CDS_Variants", "📋 Isoform／CDS 變異" },
            { "Italic", "斜體" },
            { "Label_column_width", "標籤欄寬度" },
            { "Lanes", "泳道：" },
            { "Lanthanide", "鑭系元素" },
            { "Layout_Settings", "版面設定" },
            { "Left", "← 向左" },
            { "Len", "長度：" },
            { "Length", "長度： " },
            { "Length_0_bp", "長度：0 bp" },
            { "Line", "📈 折線" },
            { "Line_Chart", "折線圖" },
            { "Line_Color", "線條顏色：" },
            { "Line_Color_2", "線條顏色" },
            { "Line_Settings", "線條設定" },
            { "Line_Style", "線條樣式：" },
            { "Line_Thickness", "線條粗細：" },
            { "Line_Thickness_2", "線條粗細" },
            { "Line_Width", "線條寬度：" },
            { "Linear", "線狀" },
            { "Linear_2", "(線性)" },
            { "Linear_Regression", "📈 線性迴歸" },
            { "Lines", "線條：" },
            { "Load_Data", "載入資料" },
            { "Load_FCS", "📂 載入 FCS" },
            { "Load_File", "📂 載入檔案" },
            { "Load_Image_File", "📂  載入影像檔…" },
            { "Load_Sample_Data", "📋 載入範例資料" },
            { "Load_Selected_Vector", "📥 載入所選載體" },
            { "Load_built_in_4_color_demo_FCS_file_FITC_PE", "載入內建的 4 色範例 FCS 檔 (FITC / PE / PE-Cy5 / APC)" },
            { "Load_sample_data_for_current_chart_type", "載入目前圖表類型的範例資料" },
            { "Loading", "載入中…" },
            { "Log2_FC_Threshold", "Log2 FC 閾值：" },
            { "Log_Scale", "對數刻度" },
            { "Logarithmic_Scale_Log10", "對數刻度 (Log10)" },
            { "Low_Expression_Group", "🔵 低表現組" },
            { "Low_bottom", " ，低：後 " },
            { "Lower_only", "僅下方" },
            { "M_W_Calculator", "分子量計算器" },
            { "M_W_g_mol", "分子量 (g/mol)：" },
            { "Main_Scale_Major_Ticks", "主刻度" },
            { "Main_Title", "主標題：" },
            { "Manual_Analyze_find_complement", "手動 — 分析／尋找互補股" },
            { "Marker", "標記" },
            { "Marker_Shape", "標記形狀：" },
            { "Marker_Size", "標記大小：" },
            { "Marker_Type", "Marker 類型：" },
            { "Mass", "質量：" },
            { "Math_Symbols", "數學符號" },
            { "Max", "最大" },
            { "Max_2", "最大：" },
            { "Max_Length", "最長長度" },
            { "Max_Product_bp", "最長產物 (bp)" },
            { "Max_Tm_C", "最大 ΔTm (°C)" },
            { "Max_Tm_C_2", "最高 Tm (°C)" },
            { "Maximum", "最大值：" },
            { "Mean_SD_SEM_Min_Max_Median_for_each_series", "各數列的平均值、SD、SEM、最小值、最大值與中位數" },
            { "Metalloid", "類金屬" },
            { "Min", "最小" },
            { "Min_2", "最小：" },
            { "Min_Length", "最短長度" },
            { "Min_Product_bp", "最短產物 (bp)" },
            { "Min_Tm_C", "最低 Tm (°C)" },
            { "Min_r", "最小 |r|：" },
            { "Minimum", "最小值：" },
            { "Mode", "模式：" },
            { "Molecular_Weight", "分子量" },
            { "Molecular_Weight_Calculator", "分子量計算器" },
            { "Molecular_Weight_Calculator_2", "⚖️ 分子量計算器" },
            { "Molecular_Weight_Calculator_Peptide_and_comp", "⚖️  分子量計算器  —  胜肽與化合物分子量計算" },
            { "Monovalent_cation_concentration_mM", "單價陽離子濃度 (mM)" },
            { "Mouse_NCBI", "小鼠 (NCBI)" },
            { "Multi_Factors", "📊  多因子" },
            { "Multi_Factors_2", "📊 多因子" },
            { "Multi_Factors_Bar_Chart", "多因子長條圖" },
            { "Multi_Select", "多選" },
            { "Multiple_Matches", "ℹ️ 多重比對" },
            { "Multiple_cuts_2", "多切位 (2+)" },
            { "N0_auto", "(0 = 自動)" },
            { "N0_bp", "0 bp" },
            { "N0_genes", "0 個基因" },
            { "N0_genes_2", " (0 個基因)" },
            { "N1_Samples_Input_OD_Values", "1. 樣本輸入 (OD 值)" },
            { "N1_ins", "+1 插入" },
            { "N2025_BioXAK_All_rights_reserved", "© 2025 BioXAK. 版權所有。" },
            { "N2D_Scatter_Plot", "2D 散佈圖" },
            { "N2_Standard_Curve", "2. 標準曲線" },
            { "N2_ins", "+2 插入" },
            { "N3_Enzyme", "3' 端酶" },
            { "N3_RE", "3' 限制酶：" },
            { "N3_Recipe_Calculation_Result", "3. 配方 (計算結果)" },
            { "N3_overhang", "3' 突出端" },
            { "N4_cutter", "4 鹼基辨識" },
            { "N5_Enzyme", "5' 端酶" },
            { "N5_RE", "5' 限制酶：" },
            { "N5_overhang", "5' 突出端" },
            { "N6_cutter", "6 鹼基辨識" },
            { "N8_cutter", "8 鹼基辨識" },
            { "N95_Confidence_Interval_95_CI", "95% 信賴區間 (95% CI)" },
            { "Name", "名稱：" },
            { "New_Analysis", "← 新的分析" },
            { "Next", "下一步 →" },
            { "Next_Ctrl_N", "下一個 ▶ (Ctrl+N)" },
            { "Next_sample", "下一個樣本" },
            { "No_SPILLOVER_data_in_FCS_file", "⚠️ FCS 檔中沒有 $SPILLOVER 資料。" },
            { "No_constraint_set", "尚未設定限制條件" },
            { "No_cuts_0", "不切割 (0)" },
            { "No_file_loaded", "尚未載入檔案" },
            { "No_local_TCGA_data_detected_Click_Start_Down", "未偵測到本機 TCGA 資料。點擊「開始下載」即可自動從 Zenodo 下載所有癌症資料集 (約 3–5 GB)。下載完成後即可使用全部分析功能。" },
            { "No_region_selected", "尚未選取區域" },
            { "No_template_loaded", "尚未載入模板" },
            { "Noble_Gas", "惰性氣體" },
            { "Nonmetal", "非金屬" },
            { "Normal_Mean", "正常平均" },
            { "Normal_N", "正常 N" },
            { "Normal_Only", "僅正常" },
            { "Normal_SD", "正常 SD" },
            { "Not_Found", "⚠️ 找不到" },
            { "NucleotideComplementary", "核苷酸互補" },
            { "Nucleotide_Complementary", "核苷酸互補" },
            { "Nucleotide_Complementary_Complement_and_reve", "🔁  核苷酸互補  —  互補與反向互補序列" },
            { "Number", "數量：" },
            { "Number_of_lanes", "泳道數量：" },
            { "OD_1", "OD 1" },
            { "OD_2", "OD 2" },
            { "OD_Absorbance", "OD 吸光值" },
            { "OK", "確定" },
            { "ONGOING_PROJECTS", "🚧  開發中項目" },
            { "OR_enter_accession", "── 或輸入 Accession ──" },
            { "One_Way_ANOVA_Same_Series", "📐 單因子變異數分析 (相同數列)" },
            { "One_Way_ANOVA_Same_X", "📐 單因子變異數分析 (相同 X)" },
            { "Open_GitHub_repository_in_browser", "在瀏覽器開啟 GitHub 專案頁" },
            { "Open_NCBI_Primer_BLAST_with_current_primers", "以目前的引子開啟 NCBI Primer-BLAST" },
            { "Open_in_Scatter_Plot", "在散佈圖中開啟" },
            { "Open_saved_WB_layout_Ctrl_O", "開啟已儲存的 WB 版面 (Ctrl+O)" },
            { "Open_saved_analysis_Ctrl_O", "開啟已儲存的分析 (Ctrl+O)" },
            { "Open_saved_graph_data_Ctrl_O", "開啟已儲存的繪圖資料 (Ctrl+O)" },
            { "Open_xak", "📂 開啟 .xak" },
            { "Orientation", "方向：" },
            { "Other", "其他" },
            { "Overlay", "疊圖" },
            { "PROTEIN", "蛋白質" },
            { "PROTEIN_CHEMISTRY", "🧪  蛋白質與化學" },
            { "P_value_ascending", "P-value (由小到大)" },
            { "Palindromic", "迴文序列" },
            { "Panel_1", "面板 1" },
            { "Parameter", "參數：" },
            { "Parameter_s", "參數" },
            { "Parent", "上層" },
            { "Parent_Gate_filter_events", "上層 Gate (篩選事件)：" },
            { "Paste", "📋 貼上" },
            { "Paste_2", "貼上" },
            { "Paste_CDS_mRNA_sequence_FASTA_or_plain", "貼上 CDS/mRNA 序列 (FASTA 或純序列)" },
            { "Paste_DNA_template_sequence_ATGC", "貼上 DNA 模板序列 (ATGC)…" },
            { "Paste_Support_Click_any_cell_e_g_OD1_and_Ctr", "支援貼上：點選任一儲存格 (例如 OD1) 後按 Ctrl+V" },
            { "Paste_Transposed", "轉置貼上" },
            { "Penalize_self_complementarity_G_5_kcal_mol", "對自身互補扣分 (ΔG < -5 kcal/mol)" },
            { "Plot", "繪圖" },
            { "Plot_Type_Colors", "圖形類型與配色" },
            { "Point_Size", "資料點大小：" },
            { "Polygon", "多邊形" },
            { "Polynomial_Degree", "多項式次數：" },
            { "Pos", "位置：" },
            { "Position", "位置" },
            { "Post_transition", "後過渡金屬" },
            { "Preset_sizes", "預設尺寸" },
            { "Prev_Ctrl_P", "◀ 上一個 (Ctrl+P)" },
            { "Preview", "預覽" },
            { "Preview_2", "預覽：" },
            { "Preview_Text", "預覽文字" },
            { "Preview_top_result", "預覽 (最佳結果)：" },
            { "Previous_sample", "上一個樣本" },
            { "Primer_BLAST_NCBI", "🔬 Primer-BLAST (NCBI)" },
            { "Primer_Binding_Visualization", "📋 引子結合位置圖示" },
            { "Primer_Design", "引子設計" },
            { "Primer_Designer", "引子設計" },
            { "Primer_Designer_2", "🧬 引子設計" },
            { "Primer_Pair_Summary", "🔗 引子對總覽" },
            { "Primer_Sequences_5_3", "引子序列 (5'→3')" },
            { "Primer_concentration_nM", "引子濃度 (nM)" },
            { "Primer_nM", "引子 (nM)" },
            { "Product", "產物" },
            { "Product_must_span_selected_region", "產物須涵蓋所選區域" },
            { "Product_tolerance_bp", "產物長度容許誤差 (±bp)" },
            { "Protective_bases", "保護鹼基：" },
            { "Protein", "蛋白質" },
            { "Protein_BCA_Calculator", "蛋白質 BCA 計算器" },
            { "Protein_truncation_with_1_nucleotide_inserti", "插入 1 個核苷酸後的蛋白質截斷情形" },
            { "Protein_truncation_with_2_nucleotide_inserti", "插入 2 個核苷酸後的蛋白質截斷情形" },
            { "Quadrant", "四象限" },
            { "RESTRICTION_DIGEST", "✂️ 限制酶切割" },
            { "RESTRICTION_ENZYME", "限制酶" },
            { "RESTRICTION_ENZYME_2", "🧫  限制酶" },
            { "RE_Cutting_Site_Detector", "限制酶切位偵測" },
            { "RE_Pattern_Predictor", "限制酶圖譜預測" },
            { "RE_Pattern_Predictor_Restriction_site_detect", "🔍  限制酶圖譜預測  —  限制酶切位偵測與圖譜分析" },
            { "RE_Predictor", "限制酶預測" },
            { "RE_Predictor_Enzyme_based_digestion_predicti", "🗺️  限制酶預測  —  依酶種預測切割結果" },
            { "R_Pearson_correlation_slope_significance_for", "計算每個數列的 R²、Pearson 相關係數與斜率顯著性" },
            { "Range_Gate", "範圍 Gate" },
            { "Rat_NCBI", "大鼠 (NCBI)" },
            { "Reaction_Conditions", "🧪 反應條件" },
            { "Ready_Load_an_FCS_file_or_demo_data_to_begin", "就緒。請載入 FCS 檔或範例資料以開始。" },
            { "Ready_to_download", "準備下載…" },
            { "Recently_Used", "最近使用" },
            { "Recognition", "辨識序列" },
            { "Recommended", "⭐ = 建議使用" },
            { "Recommended_criteria", "建議條件：" },
            { "Record_Ctrl_M", "📊 記錄 (Ctrl+M)" },
            { "Record_current_gating_statistics_to_table", "將目前的圈選統計記錄至表格" },
            { "Refresh_Preview", "重新整理預覽" },
            { "Regression_Trendline", "迴歸／趨勢線" },
            { "Regulation", "調控方向" },
            { "Remove", "✕ 移除" },
            { "Remove_Panel", "➖ 移除面板" },
            { "Replicates", "重複數：" },
            { "Require_GC_clamp_3_G_or_C", "要求 GC clamp (3' 端為 G 或 C)" },
            { "Reset", "重設" },
            { "Reset_2", "↺ 重設" },
            { "Reset_All", "全部重設" },
            { "Reset_Compensation", "↺ 重設補償" },
            { "Reset_Range", "重設範圍" },
            { "Reset_Zoom", "重設縮放" },
            { "Reset_crop_selection_to_full_image", "將裁切範圍重設為整張影像" },
            { "Restriction_Enzyme_Pattern_Predictor", "限制酶圖譜預測" },
            { "Restriction_Enzyme_Predictor", "限制酶預測" },
            { "Results", "結果： " },
            { "Results_2", "結果" },
            { "Rev_5_3", "反向 (5'→3')" },
            { "Rev_5_RE", "反向 5' 限制酶" },
            { "Rev_Tm", "反向 Tm" },
            { "Rev_Tm_RE", "反向 Tm+RE" },
            { "Rev_Tm_RE_2", "反向 Tm (+RE)" },
            { "Reverse", "反向" },
            { "Reverse_2", "反向 (←)" },
            { "Reverse_Complement", "反向互補" },
            { "Reverse_Primer", "◄ 反向引子" },
            { "Reverse_Primer_enter_as_5_3", "反向引子 (請以 5'→3' 輸入)" },
            { "Reverse_strand", "反向股" },
            { "Right", "→ 向右" },
            { "Rotate_90_clockwise", "順時針旋轉 90°" },
            { "Rotate_90_counter_clockwise", "逆時針旋轉 90°" },
            { "Rotation_Flip", "旋轉與翻轉" },
            { "Row_spacing", "列間距" },
            { "Run_Analysis", "執行分析" },
            { "Same_Series", "同一數列" },
            { "Same_X_Row", "同一 X (列)" },
            { "Sample", "樣本" },
            { "Sample_Condition", "🔬 樣本條件：" },
            { "Sample_L", "樣本 (µL)" },
            { "Save_PNG", "💾 儲存 PNG" },
            { "Save_SVG", "💾 儲存 SVG" },
            { "Save_WB_layout_Ctrl_S", "儲存 WB 版面 (Ctrl+S)" },
            { "Save_analysis_state_Ctrl_S", "儲存分析狀態 (Ctrl+S)" },
            { "Save_current_graph_data_Ctrl_S", "儲存目前的繪圖資料 (Ctrl+S)" },
            { "Save_xak", "💾 儲存 .xak" },
            { "Scale", "刻度：" },
            { "Scale_2", "刻度" },
            { "Scatter", "📈 散佈圖" },
            { "Scatter_2", "⚬ 散佈" },
            { "Scatter_Plot", "散佈圖" },
            { "Score", "評分" },
            { "Search", "🔍 搜尋：" },
            { "Search_Gene", "🔍 搜尋基因：" },
            { "Search_Gene_2", "🔍 搜尋基因" },
            { "Search_Gene_from_NCBI", "🔍 從 NCBI 搜尋基因" },
            { "Search_enzyme", "搜尋限制酶…" },
            { "Search_enzyme_2", "  🔍 搜尋限制酶…" },
            { "Select_All", "全選" },
            { "Select_All_Deselect_All", "全選／全不選" },
            { "Select_Enzyme", "選擇限制酶：" },
            { "Select_Error_Bar_Type", "選擇誤差線類型" },
            { "Select_a_Color", "請選擇顏色" },
            { "Select_a_construct", "請選擇一個構築" },
            { "Select_cells_and_Ctrl_C_to_copy_or_right_cli", "💡 選取儲存格後按 Ctrl+C 複製，或按右鍵開啟選單" },
            { "Select_species_to_download_from_HGNC_NCBI", "選擇要從 HGNC/NCBI 下載的物種：" },
            { "Selected", "已選： " },
            { "Selected_Cancers", "已選癌症" },
            { "Selected_Enzyme", "已選限制酶：" },
            { "Selected_Region", "已選區域：" },
            { "Self_Comp", "自身互補" },
            { "Self_Dimer_G", "自身二聚體 ΔG" },
            { "Sequence", "序列" },
            { "Sequence_Type", "序列類型" },
            { "Series", "數列：" },
            { "Series_Settings", "數列設定" },
            { "Set_Bounds", "↔ 設定邊界" },
            { "Set_Lanes", "● 設定泳道" },
            { "Set_constraint_to_the_full_CDS_region", "將限制條件設為整段 CDS 區域" },
            { "Set_from_CDS", "🧬 由 CDS 設定" },
            { "Set_from_canvas_selection", "📌 由畫布選取設定" },
            { "Set_official_symbol_as_antibody_name", "將官方 Symbol 設為抗體名稱" },
            { "Settings_auto_apply_on_click_outside", "⚡ 點擊空白處後設定會自動套用" },
            { "Setup_Channels", "⚙️ 設定通道…" },
            { "Show_Border", "顯示邊框" },
            { "Show_Grid_Lines_at_major_ticks", "顯示格線 (位於主刻度)" },
            { "Show_enzymes_with", "顯示切割次數為：" },
            { "Show_equation_R_on_chart", "在圖上顯示方程式與 R²" },
            { "Show_individual_data_points_on_bars", "在長條上顯示個別資料點" },
            { "Show_minor_ticks", "顯示次刻度" },
            { "Show_regression_line", "顯示迴歸線" },
            { "Side_Labels", "側邊標籤" },
            { "Significant_Genes", "📋 顯著基因" },
            { "Single", "單一" },
            { "Single_Select", "單選" },
            { "Single_cut_1", "單一切位 (1)" },
            { "Size", "尺寸：" },
            { "Size_bp", "大小 (bp)" },
            { "Skip_for_Now", "暫時略過" },
            { "Some_events_with_0_values_are_excluded_from", "⚠️ 數值 ≤0 的部分事件已排除於 Log 刻度顯示之外。" },
            { "Sort_Asc", "↑ 遞增排序" },
            { "Sort_Desc", "↓ 遞減排序" },
            { "Sort_by", "排序依據：" },
            { "Species", "物種：" },
            { "Species_2", "物種" },
            { "Standard_Deviation_SD", "標準差 (SD)" },
            { "Standard_Error_of_Mean_SEM", "平均值標準誤 (SEM)" },
            { "Start_Download", "▶  開始下載" },
            { "Starts_with", "開頭為" },
            { "Statistical_Analysis", "統計分析" },
            { "Statistical_Analysis_2", "📊 統計分析" },
            { "Statistics", "📊 統計" },
            { "Statistics_Table", "📋 統計表" },
            { "Status", "狀態" },
            { "Step_1_Select_Statistical_Method", "步驟 1：選擇統計方法" },
            { "Step_2_Configure_Analysis", "步驟 2：設定分析" },
            { "Straight_Line", "直線" },
            { "Style", "樣式：" },
            { "Sub_Scale_Minor_Ticks", "次刻度" },
            { "Subscript_Superscript", "下標／上標" },
            { "Subtitle", "副標題：" },
            { "Survival_KM", "📉 存活分析 (KM)" },
            { "Symbol_2", "Ω 符號" },
            { "TCGA_Analysis", "TCGA 分析" },
            { "TCGA_Analysis_Box_plots_heatmaps_scatter_plo", "📊  TCGA 分析  —  盒鬚圖、熱圖、散佈圖、Kaplan-Meier 存活分析、火山圖" },
            { "TCGA_DATABASE", "TCGA 資料庫" },
            { "TCGA_DATABASE_2", "🧬  TCGA 資料庫" },
            { "TCGA_Database_Analysis", "TCGA 資料庫分析" },
            { "TCGA_Database_Initialization", "🧬  TCGA 資料庫初始化" },
            { "T_Test_Two_Groups", "🔬 T 檢定 (兩組)" },
            { "Target_Gene", "目標基因：" },
            { "Target_Product_bp", "目標產物長度 (bp)" },
            { "Target_Tm_C", "目標 Tm (°C)" },
            { "Target_g", "目標量 (µg)：" },
            { "Text", "📝 文字" },
            { "Text_Annotation", "文字註解" },
            { "Text_Content", "文字內容" },
            { "Threshold", "閾值" },
            { "Tick_Marks", "刻度線" },
            { "Tip_Select_cells_and_press_Ctrl_C_to_copy_or", "💡 提示：選取儲存格後按 Ctrl+C 複製，或使用「複製結果」按鈕複製全部" },
            { "Tip_Select_start_cell_to_paste", "提示：選取起始儲存格即可貼上" },
            { "Tip_You_can_change_direction_for_individual", "提示：在個別長條上按右鍵，可單獨變更其誤差線方向。" },
            { "Title", "標題：" },
            { "Titles", "標題" },
            { "Tm_Owczarzy_2008_SantaLucia_1998_NN", "Tm 計算：Owczarzy 2008 + SantaLucia 1998 NN" },
            { "Tm_full", "ΔTm (完整)" },
            { "Tm_tolerance_C", "Tm 容許誤差 (±°C)" },
            { "Top_Group_Labels", "上方群組標籤" },
            { "Topology", "拓樸結構：" },
            { "Total_Vol_L", "總體積 (µL)：" },
            { "Transition", "過渡金屬" },
            { "Treats_entire_sequence_as_one_exon_for_sgRNA", "將整段序列視為單一 exon 進行 sgRNA 設計" },
            { "Tumor_Mean", "腫瘤平均" },
            { "Tumor_N", "腫瘤 N" },
            { "Tumor_Only", "僅腫瘤" },
            { "Tumor_SD", "腫瘤 SD" },
            { "Two_Way_ANOVA", "📊 雙因子變異數分析" },
            { "Type", "類型：" },
            { "U_Shape", "ㄇ 形線" },
            { "Undo", "↩ 復原" },
            { "Up", "↑ 上移" },
            { "Update_Database", "🔄 更新資料庫" },
            { "Upper_only", "僅上方" },
            { "Use", "使用" },
            { "Use_Entire_Sequence", "使用整段序列" },
            { "Use_Selected_Region", "使用所選區域" },
            { "Use_This_Sequence", "使用此序列" },
            { "Use_in_Main_Title_for_two_lines", "(在主標題中使用 | 可分成兩行)" },
            { "Use_the_region_you_dragged_on_the_gene_visua", "使用你在基因視覺化畫布上拖曳選取的區域" },
            { "VECTOR_LIBRARY", "載體資料庫" },
            { "Vector", "載體：" },
            { "Vector_Design", "載體設計" },
            { "Vector_Designer", "載體設計" },
            { "Vector_Designer_2", "🧬 載體設計" },
            { "Version_Loading", "版本：載入中…" },
            { "View", "檢視" },
            { "View_Type", "檢視類型" },
            { "Volcano", "🌋 火山圖" },
            { "Volcano_Plot", "火山圖" },
            { "Volume", "體積：" },
            { "WB_Organizer", "WB 排版工具" },
            { "WESTERN_BLOT", "西方墨點法" },
            { "WORKSPACE", "工作區" },
            { "Water_L", "水 (µL)" },
            { "Western_Blot_Organizer", "西方墨點法排版工具" },
            { "Worm_NCBI", "線蟲 (NCBI)" },
            { "X_Axis", "X 軸" },
            { "X_Axis_Parameter", "X 軸參數：" },
            { "X_Axis_Settings", "X 軸設定" },
            { "X_Axis_Title", "X 軸標題：" },
            { "X_Column", "X 欄" },
            { "X_Index", "X 索引：" },
            { "X_Range", "X 範圍：" },
            { "X_Scale", "X 軸刻度：" },
            { "X_Y_Graph", "📈  X-Y 圖" },
            { "Y_Axis", "Y 軸" },
            { "Y_Axis_Parameter", "Y 軸參數：" },
            { "Y_Axis_Settings", "Y 軸設定" },
            { "Y_Axis_Title", "Y 軸標題：" },
            { "Y_Columns", "Y 欄" },
            { "Y_Data_Mode", "Y 資料模式" },
            { "Y_Range", "Y 範圍：" },
            { "Y_Scale", "Y 軸刻度：" },
            { "Zebrafish_NCBI", "斑馬魚 (NCBI)" },
            { "Zoom", "縮放：" },
            { "Zoom_In", "放大" },
            { "Zoom_Out", "縮小" },
            { "before_PAM_GC_content", "(PAM 之前) + GC 含量" },
            { "dNTP_concentration_mM", "dNTP 濃度 (mM)" },
            { "data_spread", " － 資料離散程度" },
            { "per_major_tick", "每一主刻度" },
            { "precision", " － 平均值的精確度" },
            { "r_descending", "|r| (由大到小)" },
            { "r_descending_2", "r (由大到小)" },
            { "sgRNA_Candidates", "🎯 sgRNA 候選" },
            { "sgRNA_Designer", "sgRNA 設計" },
            { "sgRNA_Designer_Guide_RNA_design_with_gene_st", "🔬  sgRNA 設計  —  導引 RNA 設計，含基因結構視覺化與框移分析" },
            { "sgRNA_Sequence_5_3", "sgRNA 序列 (5'→3')" },
        };
    }
}
